# Generated by Django 4.2.3 on 2023-08-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_remove_follower_follower_alter_follower_user_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follower",
            unique_together={("user", "follower")},
        ),
    ]
