# Generated by Django 4.2.3 on 2023-08-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_like_user_alter_like_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="liked",
        ),
    ]
